###  USUARIOS
GET http://comedor.mercal.gob.ve/api/p1/users HTTP/1.1
content-type: application/json
Authorization: Bearer 32|7MX5Ed22cu26DKvQz3nbCYcRZ1YQBzFxCpe1r0cT8d364ebf
### MENU
GET  http://comedor.mercal.gob.ve/api/p1/menus HTTP/1.1
content-type: application/json
Authorization: Bearer 38|xsGg52ysl8hlw4d4N4n4n3B98BQchyksXqFFuuMAad791286
### ORDERS
GET  http://comedor.mercal.gob.ve/api/p1/ordersDay HTTP/1.1
content-type: application/json
Authorization: Bearer 29|Fa2mBV1bwPTRJvZVHDWl0rVCT9CGtJDPiQJk4GNUe173ce7d
### EXTRAS
GET http://comedor.mercal.gob.ve/api/p1/extras HTTP/1.1
content-type: application/json
Authorization: Bearer 29|Fa2mBV1bwPTRJvZVHDWl0rVCT9CGtJDPiQJk4GNUe173ce7d
### GERENCIAS TODAS
GET http://comedor.mercal.gob.ve/api/p1/gerencias HTTP/1.1
content-type: application/json
Authorization: Bearer 4|HzW2YI4FVZwN2c6aX3MqppZlGkYEZEoQxfu108vD5f2c5289
###  GERENCIA x ID
GET http://comedor.mercal.gob.ve/api/p1/gerencias/1 HTTP/1.1
content-type: application/json
Authorization: Bearer 4|HzW2YI4FVZwN2c6aX3MqppZlGkYEZEoQxfu108vD5f2c5289
###  PEDIDOS
GET http://comedor.mercal.gob.ve/api/p1/pedidos HTTP/1.1
content-type: application/json
Authorization: Bearer 8|DFjFp7ZFJSYqBvGqyl3l1V09zcv8ONT55Y1OGjDl12accd71

###  EMPLEADOS
GET http://comedor.mercal.gob.ve/api/p1/empleados HTTP/1.1
content-type: application/json
Authorization: Bearer 29|Fa2mBV1bwPTRJvZVHDWl0rVCT9CGtJDPiQJk4GNUe173ce7d
*******************************POSTS******************************
#### LOGIN
POST http://comedor.mercal.gob.ve/api/p1/users/login HTTP/1.1
content-type: application/json

{
    "email": "moicastillo@mercal.gob.ve",
    "password": "12345678"
}